import type { Locale } from "@/lib/locale"
import type { ProjectsCopy } from "@/content/types"

export const projectsCopy = {
    en: {
        eyebrow: "Selected work",
        title: "Projects",
        summary: "Applied work connecting AI models, data pipelines, APIs, and clear interfaces to real problems.",
        viewDetails: "View project details",
        contextLabel: "Context",
        roleLabel: "Role",
        specificationsLabel: "Project specifications",
        technologiesLabel: "Technologies",
        imageZoomLabel: "Enlarge project image",
        closeImageLabel: "Close enlarged image",
        items: [
            {
                number: "/0.1",
                title: "ENETRIX RAG Chatbot",
                description: "A natural-language assistant connected to a vector database for querying energy agreements in the ENETRIX platform.",
                category: "Applied AI",
                context: "Applied research at TRIL Lab",
                role: "Researcher and developer",
                specifications: [
                    "Designed intelligent SQL queries and embedding-based semantic retrieval.",
                    "Integrated the workflow in n8n with OpenRouter APIs and Supabase.",
                    "Improved how information stored in the platform can be located and queried.",
                ],
                technologies: ["Python", "RAG", "Embeddings", "Vector database", "PostgreSQL", "Supabase", "n8n", "OpenRouter", "APIs"],
                link: {
                    href: "https://enetrix.ufpb.br/pt/chatbot-brasil",
                    label: "Open live chatbot",
                },
                image: {
                    src: "/images/projects/enetrix-rag-chatbot.jpg",
                    alt: "ENETRIX chatbot interface answering a question about renewable-energy agreements between Brazil and China",
                    caption: "ENETRIX RAG chatbot interface",
                    width: 1920,
                    height: 921,
                },
            },
            {
                number: "/0.2",
                title: "Stock Analyzer Bot",
                description: "A Python platform combining market data, financial news, AI sentiment agents, predictive models, and interactive interfaces.",
                category: "AI & Data Engineering",
                context: "Doctoral research at TRIL Lab",
                role: "Researcher, developer, and team lead",
                specifications: [
                    "Built a FastAPI backend with REST endpoints and Server-Sent Events for incremental price and forecast streaming.",
                    "Created Streamlit market, chat, and financial report experiences with Plotly candlesticks and confidence ranges.",
                    "Collected and normalized financial news from Money Times, Yahoo Finance, and Investidor10.",
                    "Developed sentiment and reporting agents, with MongoDB persistence and OHLCV acquisition through yfinance.",
                    "Experimented with LSTM, GRU, and DNN models and compared sentiment signals from GPT-4o, Gemma, and Llama.",
                ],
                technologies: ["Python 3.12", "Streamlit", "FastAPI", "SSE", "pandas", "yfinance", "TensorFlow", "Keras", "scikit-learn", "SciPy", "Plotly", "MongoDB", "Agno", "LangChain", "Crawl4AI", "Docker"],
                link: null,
                image: {
                    src: "/images/projects/stock-analyzer-forecast.png",
                    alt: "AAPL34 future-price forecast timeline produced by the Stock Analyzer Bot",
                    caption: "Future-price forecast visualization for AAPL34",
                    width: 1208,
                    height: 532,
                },
            },
            {
                number: "/0.3",
                title: "IJVM Virtual Machine",
                description: "A basic Integer Java Virtual Machine implementation capable of executing instructions from the IJVM architecture.",
                category: "Computer Architecture",
                context: "Academic Computer Architecture project",
                role: "Developer in a team",
                specifications: [
                    "Implemented registers, virtual memory, and an arithmetic logic unit in C++.",
                    "Translated basic IJVM instructions into operations executed against virtual memory.",
                    "Applied low-level programming and computer architecture concepts in an executable system.",
                ],
                technologies: ["C++", "Computer architecture", "Virtual memory", "Registers", "ALU"],
                link: null,
                image: null,
            },
        ],
    },
    pt: {
        eyebrow: "Trabalhos selecionados",
        title: "Projetos",
        summary: "Projetos que conectam modelos de IA, pipelines de dados, APIs e interfaces claras a problemas reais.",
        viewDetails: "Ver detalhes do projeto",
        contextLabel: "Contexto",
        roleLabel: "Papel",
        specificationsLabel: "Especificações do projeto",
        technologiesLabel: "Tecnologias",
        imageZoomLabel: "Ampliar imagem do projeto",
        closeImageLabel: "Fechar imagem ampliada",
        items: [
            {
                number: "/0.1",
                title: "Chatbot RAG ENETRIX",
                description: "Assistente em linguagem natural conectado a um banco vetorial para consultar acordos energéticos da plataforma ENETRIX.",
                category: "IA aplicada",
                context: "Pesquisa aplicada no TRIL Lab",
                role: "Pesquisador e desenvolvedor",
                specifications: [
                    "Estruturação de consultas SQL inteligentes e recuperação semântica baseada em embeddings.",
                    "Integração construída em n8n com APIs da OpenRouter e Supabase.",
                    "Melhoria da forma de localizar e consultar informações armazenadas na plataforma.",
                ],
                technologies: ["Python", "RAG", "Embeddings", "Banco vetorial", "PostgreSQL", "Supabase", "n8n", "OpenRouter", "APIs"],
                link: {
                    href: "https://enetrix.ufpb.br/pt/chatbot-brasil",
                    label: "Abrir chatbot",
                },
                image: {
                    src: "/images/projects/enetrix-rag-chatbot.jpg",
                    alt: "Interface do chatbot ENETRIX respondendo a uma pergunta sobre acordos de energia renovável entre Brasil e China",
                    caption: "Interface do chatbot RAG da ENETRIX",
                    width: 1920,
                    height: 921,
                },
            },
            {
                number: "/0.2",
                title: "Stock Analyzer Bot",
                description: "Plataforma em Python que reúne dados de mercado, notícias financeiras, agentes de sentimento, modelos preditivos e interfaces interativas.",
                category: "IA e engenharia de dados",
                context: "Pesquisa de doutorado no TRIL Lab",
                role: "Pesquisador, desenvolvedor e líder de equipe",
                specifications: [
                    "Backend FastAPI com endpoints REST e Server-Sent Events para transmitir preços e previsões incrementalmente.",
                    "Interfaces Streamlit de mercado, chat e relatório financeiro com candlesticks Plotly e faixas de confiança.",
                    "Coleta e normalização de notícias do Money Times, Yahoo Finance e Investidor10.",
                    "Agentes de sentimento e relatório, persistência em MongoDB e aquisição de séries OHLCV pelo yfinance.",
                    "Experimentos com LSTM, GRU e DNN e comparação de sinais de GPT-4o, Gemma e Llama.",
                ],
                technologies: ["Python 3.12", "Streamlit", "FastAPI", "SSE", "pandas", "yfinance", "TensorFlow", "Keras", "scikit-learn", "SciPy", "Plotly", "MongoDB", "Agno", "LangChain", "Crawl4AI", "Docker"],
                link: null,
                image: {
                    src: "/images/projects/stock-analyzer-forecast.png",
                    alt: "Linha do tempo da previsão futura de preço da AAPL34 produzida pelo Stock Analyzer Bot",
                    caption: "Visualização da previsão futura de preço da AAPL34",
                    width: 1208,
                    height: 532,
                },
            },
            {
                number: "/0.3",
                title: "Máquina virtual IJVM",
                description: "Implementação básica de uma Integer Java Virtual Machine capaz de executar instruções da arquitetura IJVM.",
                category: "Arquitetura de computadores",
                context: "Projeto acadêmico de Arquitetura de Computadores",
                role: "Desenvolvedor em equipe",
                specifications: [
                    "Implementação em C++ de registradores, memória virtual e unidade lógica e aritmética.",
                    "Tradução de instruções básicas da IJVM para operações executadas sobre a memória virtual.",
                    "Aplicação de programação de baixo nível e arquitetura de computadores em um sistema executável.",
                ],
                technologies: ["C++", "Arquitetura de computadores", "Memória virtual", "Registradores", "ULA"],
                link: null,
                image: null,
            },
        ],
    },
} satisfies Record<Locale, ProjectsCopy>
