import type { Locale } from "@/lib/locale"
import type { SiteShellCopy } from "@/content/types"

export const siteShellCopy = {
    en: {
        documentLanguage: "en",
        skipToContent: "Skip to main content",
        mainLabel: "Samuel Jales portfolio",
        metadata: {
            title: "Samuel Jales — Software & AI Engineer",
            description: "Portfolio of Samuel Jales, a Software & AI engineer working with applied AI, RAG, machine learning, data, and web development.",
        },
        navigation: {
            primaryNavigation: "Primary navigation",
            actions: "Portfolio actions",
            search: "Search the portfolio",
            enableDarkMode: "Enable dark mode",
            enableLightMode: "Enable light mode",
            moreOptions: "Open contact options",
            contactMenu: "Contact and language options",
            language: "Language",
            english: "English",
            portuguese: "Português",
            selectEnglish: "Use English",
            selectPortuguese: "Usar Português",
            currentLanguage: "current language",
            connect: "Connect with me",
            email: "Email Samuel Jales",
            linkedin: "Open Samuel Jales on LinkedIn in a new tab",
            github: "Open Samuel Jales on GitHub in a new tab",
            resume: "Résumé",
            resumeLabel: "Download Samuel Jales's résumé",
        },
        footer: {
            landmark: "Portfolio footer",
            navigationLabel: "Footer navigation",
            languageLabel: "Choose language",
            projects: "Projects",
            about: "About",
            experience: "Experience",
            contact: "Contact",
            english: "English",
            portuguese: "Português",
            selectEnglish: "Use English",
            selectPortuguese: "Usar Português",
            currentLanguage: "current language",
            copyright: "© 2026 Samuel Jales",
        },
    },
    pt: {
        documentLanguage: "pt-BR",
        skipToContent: "Pular para o conteúdo principal",
        mainLabel: "Portfólio de Samuel Jales",
        metadata: {
            title: "Samuel Jales — Engenheiro de Software e IA",
            description: "Portfólio de Samuel Jales, engenheiro de Software e IA com atuação em IA aplicada, RAG, machine learning, dados e desenvolvimento web.",
        },
        navigation: {
            primaryNavigation: "Navegação principal",
            actions: "Ações do portfólio",
            search: "Pesquisar no portfólio",
            enableDarkMode: "Ativar modo escuro",
            enableLightMode: "Ativar modo claro",
            moreOptions: "Abrir opções de contato",
            contactMenu: "Opções de contato e idioma",
            language: "Idioma",
            english: "English",
            portuguese: "Português",
            selectEnglish: "Usar inglês",
            selectPortuguese: "Usar Português",
            currentLanguage: "idioma atual",
            connect: "Entre em contato",
            email: "Enviar e-mail para Samuel Jales",
            linkedin: "Abrir o LinkedIn de Samuel Jales em uma nova aba",
            github: "Abrir o GitHub de Samuel Jales em uma nova aba",
            resume: "Currículo",
            resumeLabel: "Baixar o currículo de Samuel Jales",
        },
        footer: {
            landmark: "Rodapé do portfólio",
            navigationLabel: "Navegação do rodapé",
            languageLabel: "Escolher idioma",
            projects: "Projetos",
            about: "Sobre",
            experience: "Experiência",
            contact: "Contato",
            english: "English",
            portuguese: "Português",
            selectEnglish: "Usar inglês",
            selectPortuguese: "Usar Português",
            currentLanguage: "idioma atual",
            copyright: "© 2026 Samuel Jales",
        },
    },
} satisfies Record<Locale, SiteShellCopy>
